name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
            cd src
            make
    - name: make install
      run: |
            cd src
            export PREFIX="/usr/local"
            sudo make install
    - name: check files
      run: which wireguard
